//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace octalforty.Wizardby.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BindingCompilerStage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BindingCompilerStage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("octalforty.Wizardby.Core.Resources.BindingCompilerStage", typeof(BindingCompilerStage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve Foreign Key Column or Foreign Key Columns for Add Reference &apos;{0}&apos;. You might be missing &apos;fk-column&apos; or &apos;fk-columns&apos; property or &apos;add reference&apos; is nested incorrectly..
        /// </summary>
        internal static string CouldNotResolveFkColumnForAddReference {
            get {
                return ResourceManager.GetString("CouldNotResolveFkColumnForAddReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve Foreign Key Table for Add Reference &apos;{0}&apos;. You might be missing a &apos;fk-table&apos; property or &apos;add reference&apos; is nested incorrectly..
        /// </summary>
        internal static string CouldNotResolveFkTableForAddReference {
            get {
                return ResourceManager.GetString("CouldNotResolveFkTableForAddReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve Primary Key Table for Add Reference &apos;{0}&apos;. You might be missing a &apos;pk-table&apos; property..
        /// </summary>
        internal static string CouldNotResolvePkTableForAddReference {
            get {
                return ResourceManager.GetString("CouldNotResolvePkTableForAddReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve Table for Add Index &apos;{0}&apos;. You might be missing a &apos;table&apos; property or &apos;add index&apos; is nested incorrectly..
        /// </summary>
        internal static string CouldNotResolveTableForAddIndex {
            get {
                return ResourceManager.GetString("CouldNotResolveTableForAddIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve Table for Remove Index &apos;{0}&apos;. You might be missing a &apos;table&apos; property or &apos;remove index&apos; is nested incorrectly..
        /// </summary>
        internal static string CouldNotResolveTableForRemoveIndex {
            get {
                return ResourceManager.GetString("CouldNotResolveTableForRemoveIndex", resourceCulture);
            }
        }
    }
}
