//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace octalforty.Wizardby.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MdlParser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MdlParser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("octalforty.Wizardby.Core.Resources.MdlParser", typeof(MdlParser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected migration name (string or symbol) for &apos;migration&apos; element at {0}..
        /// </summary>
        internal static string ExpectedMigrationNameForMigrationAt {
            get {
                return ResourceManager.GetString("ExpectedMigrationNameForMigrationAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected version number (integer) for &apos;version&apos; element at {0}..
        /// </summary>
        internal static string ExpectedVersionNumberForVersionAt {
            get {
                return ResourceManager.GetString("ExpectedVersionNumberForVersionAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect layout at {0}..
        /// </summary>
        internal static string IncorrectLayoutAt {
            get {
                return ResourceManager.GetString("IncorrectLayoutAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of input while parsing &apos;{0}&apos;..
        /// </summary>
        internal static string UnexpectedEndOfInputWhileParsing {
            get {
                return ResourceManager.GetString("UnexpectedEndOfInputWhileParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected &apos;{0}&apos; ({1}) at {2}..
        /// </summary>
        internal static string UnexpectedTokenAt {
            get {
                return ResourceManager.GetString("UnexpectedTokenAt", resourceCulture);
            }
        }
    }
}
