//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace octalforty.Wizardby.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("octalforty.Wizardby.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to octalforty Wizardby {0} Alpha 1.
        ///Copyright (c) 2009 octalforty studios.
        /// </summary>
        internal static string CopyrightInformation {
            get {
                return ResourceManager.GetString("CopyrightInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to migration &quot;{0}&quot; revision =&gt; 1:
        ///    defaults:
        ///        default-primary-key ID type =&gt; Int32, primary-key =&gt; true, nullable =&gt; false
        ///
        ///    version {1:yyyyMMddHHmmss}:
        ///        /* Start writing migrations */.
        /// </summary>
        internal static string MdlTemplate {
            get {
                return ResourceManager.GetString("MdlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: 
        ///    wizardby &lt;command&gt; &lt;version-or-step&gt; [/mdl:&lt;mdl-file&gt;] 
        ///        [/connection:&lt;connection-string&gt;] [/platform:&lt;platform-alias&gt;] 
        ///        [/environment:&lt;environment-name&gt;]
        ///				
        ///    /mdl or /m          - Specifies the name of a MDL file	 
        ///    /connection or /c   - Specifies the connection string
        ///    /platform or /p     - Specifies the platform alias
        ///    /environment or /e  - Specifies the environment name or prefix 
        ///                          within a &quot;database.wdi&quot; file.
        ///	
        ///    If &quot;/m&quot; is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UsageInformation {
            get {
                return ResourceManager.GetString("UsageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deployment:
        ///    environment development
        ///        platform            =&gt; sqlserver 
        ///        host                =&gt; &quot;(local)\sqlexpress&quot;
        ///        database            =&gt; {0}_dev
        ///        integrated-security =&gt; true.
        /// </summary>
        internal static string WdiTemplate {
            get {
                return ResourceManager.GetString("WdiTemplate", resourceCulture);
            }
        }
    }
}
